// src/app/layout.tsx

"use client"; // 将其标记为客户端组件

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 1. 导入 WagmiProvider 和我们的配置
import { WagmiProvider } from 'wagmi';
import { config } from '@/lib/wagmi'; // @/ 是 Next.js 的路径别名，指向 src

// 2. 导入 React-Query 的 Provider
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const inter = Inter({ subsets: ["latin"] });

// 3. 创建一个 QueryClient 实例
const queryClient = new QueryClient();

// 注释掉或删除自动生成的 metadata，因为它在客户端组件中不起作用
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 4. 用 Provider 包裹整个应用 */}
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}