export default [
  {
    label: "Description (system propmt)",
    def: "",
    maxlen: 1000,
    name: "prompt",
  },
  {
    tip: `This sets the upper limit for the number of tokens the model can generate in response. It won't produce more than this limit. The maximum value is the context length minus the prompt length.`,
    label: "Max Tokens",
    min: 0,
    max: 128000,
    def: 0,
    name: "max_tokens",
    step: 100,
    is_body: true,
  },
  {
    tip: `Specifies the maximum number of chat message to be included in each request.`,
    label: "Chat Memory",
    min: 2,
    max: 12,
    name: "chatMemory",
    def: 3,
  },
  {
    tip: `This setting influences the variety in the model's responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.`,
    label: "Temperature",
    min: 0,
    max: 2,
    name: "temperature",
    def: 1.0,
    step: 0.01,
    is_body: true,
  },
  {
    tip: `This setting limits the model's choices to a percentage of likely tokens: only the top tokens whose probabilities add up to P. A lower value makes the model's responses more predictable, while the default setting allows for a full range of token choices. Think of it like a dynamic Top-K.`,
    label: "Top P",
    min: 0,
    max: 1,
    name: "top_p",
    def: 1.0,
    step: 0.01,
    is_body: true,
  },
  {
    tip: `This limits the model's choice of tokens at each step, making it choose from a smaller set. A value of 1 means the model will always pick the most likely next token, leading to predictable results. By default this setting is disabled, making the model to consider all choices.`,
    label: "Top K",
    min: 0,
    max: 100,
    name: "top_k",
    def: 0,
    is_body: true,
  },
  {
    tip: `This setting aims to control the repetition of tokens based on how often they appear in the input. It tries to use less frequently those tokens that appear more in the input, proportional to how frequently they occur. Token penalty scales with the number of occurrences. Negative values will encourage token reuse.`,
    label: "Frequency Penalty",
    min: -2,
    max: 2,
    name: "frequency_penalty",
    def: 0,
    step: 0.01,
    is_body: true,
  },
  {
    tip: `Adjusts how often the model repeats specific tokens already used in the input. Higher values make such repetition less likely, while negative values do the opposite. Token penalty does not scale with the number of occurrences. Negative values will encourage token reuse.`,
    label: "Presence Penalty",
    min: -2,
    max: 2,
    name: "presence_penalty",
    def: 0,
    step: 0.01,
    is_body: true,
  },
  {
    tip: `Helps to reduce the repetition of tokens from the input. A higher value makes the model less likely to repeat tokens, but too high a value can make the output less coherent (often with run-on sentences that lack small words). Token penalty scales based on original token's probability.`,
    label: "Repetition Penalty",
    min: 0,
    max: 2,
    name: "repetition_penalty",
    def: 1,
    step: 0.01,
    is_body: true,
  },
  {
    tip: `Represents the minimum probability for a token to be considered, relative to the probability of the most likely token. (The value changes depending on the confidence level of the most probable token.) If your Min-P is set to 0.1, that means it will only allow for tokens that are at least 1/10th as probable as the best possible option.`,
    label: "Min P",
    min: 0,
    max: 1,
    name: "min_p",
    def: 0,
    step: 0.01,
    is_body: true,
  },
  {
    tip: `Consider only the top tokens with "sufficiently high" probabilities based on the probability of the most likely token. Think of it like a dynamic Top-P. A lower Top-A value focuses the choices based on the highest probability token but with a narrower scope. A higher Top-A value does not necessarily affect the creativity of the output, but rather refines the filtering process based on the maximum probability.`,
    label: "Top A",
    min: 0,
    max: 1,
    name: "top_a",
    def: 0,
    step: 0.01,
    is_body: true,
  },
];
