export const massPayoutAbi = [
  {
    type: "function",
    name: "estimateTotal",
    inputs: [{ name: "amounts", type: "uint256[]" }],
    outputs: [{ name: "total", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sendERC20",
    inputs: [
      { name: "token", type: "address" },
      { name: "recipients", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "metadataURI", type: "string" },
    ],
    outputs: [{ name: "batchId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sendNative",
    inputs: [
      { name: "recipients", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "metadataURI", type: "string" },
    ],
    outputs: [{ name: "batchId", type: "bytes32" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "scheduleERC20",
    inputs: [
      { name: "token", type: "address" },
      { name: "recipients", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "metadataURI", type: "string" },
      { name: "executeAfter", type: "uint256" },
    ],
    outputs: [{ name: "scheduleId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "scheduleNative",
    inputs: [
      { name: "recipients", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "metadataURI", type: "string" },
      { name: "executeAfter", type: "uint256" },
    ],
    outputs: [{ name: "scheduleId", type: "bytes32" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "executeScheduled",
    inputs: [
      { name: "scheduleId", type: "bytes32" },
      { name: "recipients", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelScheduled",
    inputs: [{ name: "scheduleId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "scheduledBatches",
    inputs: [{ name: "scheduleId", type: "bytes32" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "asset", type: "address" },
      { name: "isNative", type: "bool" },
      { name: "executeAfter", type: "uint64" },
      { name: "createdAt", type: "uint64" },
      { name: "totalAmount", type: "uint256" },
      { name: "recipientsCount", type: "uint256" },
      { name: "recipientsHash", type: "bytes32" },
      { name: "executed", type: "bool" },
      { name: "metadataURI", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PayoutExecuted",
    inputs: [
      { name: "batchId", type: "bytes32", indexed: true },
      { name: "asset", type: "address", indexed: true },
      { name: "totalAmount", type: "uint256", indexed: false },
      { name: "totalRecipients", type: "uint256", indexed: false },
      { name: "payer", type: "address", indexed: true },
      { name: "payoutType", type: "uint8", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ScheduledPayoutCreated",
    inputs: [
      { name: "scheduleId", type: "bytes32", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "asset", type: "address", indexed: true },
      { name: "totalAmount", type: "uint256", indexed: false },
      { name: "executeAfter", type: "uint64", indexed: false },
      { name: "isNative", type: "bool", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ScheduledPayoutExecuted",
    inputs: [
      { name: "scheduleId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ScheduledPayoutCancelled",
    inputs: [{ name: "scheduleId", type: "bytes32", indexed: true }],
  },
] as const;
